
defaults: &defaults
  adapter:  mysql2
  encoding: utf8
  username: <%= Figaro.env.database_username %>
  password: <%= Figaro.env.database_password %>
  host:     localhost
  pool:     5
  min_messages: warning

development:
  database: <%= Figaro.env.database_name || "#{Figaro.env.app_name}_development" %>
  <<: *defaults

test:
  database: <%= Figaro.env.app_name %>_test
  <<: *defaults

production:
  database: <%= Figaro.env.database_name || "#{Figaro.env.app_name}_production" %>
  <<: *defaults

staging:
  database: <%= Figaro.env.database_name || "#{Figaro.env.app_name}_staging" %>
  <<: *defaults
